
CREATE TABLE ASSISTENCIA_ES.RM_ATENDIMENTO (
    id UUID PRIMARY KEY,
    prestador_id VARCHAR (64),
    cliente_id VARCHAR(64),
    cliente_nome VARCHAR(128) NOT NULL,
    cliente_tipo_de_doc_fiscal VARCHAR(16) NOT NULL,
    cliente_doc_fiscal VARCHAR(18) NOT NULL,
    cliente_telefone_numero VARCHAR(16) NOT NULL,
    cliente_telefone_tipo VARCHAR(12),
    cliente_whatsapp_numero VARCHAR(16),
    cliente_whatsapp_tipo VARCHAR(12),
    veiculo_placa VARCHAR(16) NOT NULL,
    tipo_ocorrencia VARCHAR(256) NOT NULL,
    servico_id VARCHAR(64) NOT NULL,
    servico_nome VARCHAR(64) NOT NULL,
    status VARCHAR(50) NOT NULL,
    data_hora_solicitado TIMESTAMP NOT NULL,
    data_hora_confirmado TIMESTAMP,
    data_hora_ajustado TIMESTAMP,
    data_hora_finalizado TIMESTAMP,
    data_hora_cancelado TIMESTAMP,
    descricao TEXT,
    base_endereco_tipo VARCHAR(16),
    base_endereco_logradouro VARCHAR(128) NOT NULL,
    base_endereco_numero VARCHAR(16) NOT NULL,
    base_endereco_complemento VARCHAR(512) NOT NULL,
    base_endereco_bairro VARCHAR(32) NOT NULL,
    base_endereco_cidade VARCHAR(32) NOT NULL,
    base_endereco_estado VARCHAR(2) NOT NULL,
    base_endereco_cep VARCHAR(12) NOT NULL,
    origem_endereco_tipo VARCHAR(16),
    origem_endereco_logradouro VARCHAR(128) NOT NULL,
    origem_endereco_numero VARCHAR(16) NOT NULL,
    origem_endereco_complemento VARCHAR(512) NOT NULL,
    origem_endereco_bairro VARCHAR(32) NOT NULL,
    origem_endereco_cidade VARCHAR(32) NOT NULL,
    origem_endereco_estado VARCHAR(2) NOT NULL,
    origem_endereco_cep VARCHAR(12) NOT NULL,
    destino_endereco_tipo VARCHAR(16),
    destino_endereco_logradouro VARCHAR(128),
    destino_endereco_numero VARCHAR(16),
    destino_endereco_complemento VARCHAR(512),
    destino_endereco_bairro VARCHAR(32),
    destino_endereco_cidade VARCHAR(32),
    destino_endereco_estado VARCHAR(2),
    destino_endereco_cep VARCHAR(12),
    version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSISTENCIA_ES.RM_ATENDIMENTO_ITEM (
  atendimento_id UUID NOT NULL REFERENCES ASSISTENCIA_ES.RM_ATENDIMENTO (id),
  nome VARCHAR (32) NOT NULL,
  unidade_de_medida VARCHAR (16) NOT NULL,
  preco_unitario INTEGER NOT NULL,
  quantidade INTEGER NOT NULL,
  observacao TEXT,
  PRIMARY KEY (nome, atendimento_id)
);

CREATE INDEX IF NOT EXISTS IDX_RM_ATENDIMENTO_ITEM_ATENDIMENTO_ID ON ASSISTENCIA_ES.RM_ATENDIMENTO_ITEM (atendimento_id);